<?php

require_once 'kuis.php';

$a = new identitas('Asep','Bandung','XI RPL 2','Single');
echo "no   :1<br>";
echo "Namanya ...".$a->get_nama();
echo "<br>";
echo "Tempat Lahir ...".$a->get_tempatlahir();
echo "<br>";
echo "Kelas ...".$a->get_kelas();
echo "<br>";
echo "Status ...".$a->get_status();
echo "<br>";
echo "_________________________________<br>";
$b = new identitas('Michael ','Bandung','XI RPL 2','Duda');
echo "no   :2<br>";
echo "Namanya ...".$b->get_nama();
echo "<br>";
echo "Tempat Lahir ...".$b->get_tempatlahir();
echo "<br>";
echo "Kelas ...".$b->get_kelas();
echo "<br>";
echo "Status ...".$b->get_status();
echo "<br>";
echo "__________________________________<br>";
$c = new identitas('Susilo','Bandung','XI RPL 2','Menikah');
echo "no   :3<br>";
echo "Namanya ...".$c->get_nama();
echo "<br>";
echo "Tempat Lahir ...".$c->get_tempatlahir();
echo "<br>";
echo "Kelas ...".$c->get_kelas();
echo "<br>";
echo "Status ...".$c->get_status();
echo "<br>";
echo "__________________________________<br>";
$c = new identitas('Dede Purnomo','Bandung','XI RPL 2','Menikah');
echo "no   :4<br>";
echo "Namanya ...".$c->get_nama();
echo "<br>";
echo "Tempat Lahir ...".$c->get_tempatlahir();
echo "<br>";
echo "Kelas ...".$c->get_kelas();
echo "<br>";
echo "Status ...".$c->get_status();
echo "<br>";
echo "_________________________________<br>";
$c = new identitas('Mas Adam','Bandung','XI RPL 2','Single');
echo "no   :5<br>";
echo "Namanya ...".$c->get_nama();
echo "<br>";
echo "Tempat Lahir ...".$c->get_tempatlahir();
echo "<br>";
echo "Kelas ...".$c->get_kelas();
echo "<br>";
echo "Status ...".$c->get_status();
echo "<br>";
echo "__________________________________<br>";
?>